apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/java-quarkus-1/base
- components/java-quarkus-10/base
- components/java-quarkus/base
- components/nodejs/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
