apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-3
    app.kubernetes.io/part-of: test-app2
  name: java-quarkus-3
  namespace: christianvogt
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-3
status:
  loadBalancer: {}
